name: java build pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout src code
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookstore_api_src_code
          path: bookstoreapi

  build:
    needs: checkout
    runs-on: ubuntu-latest
      
    steps:  
      - name: download src code
        uses: actions/download-artifact@v4
        with:
          name: bookstore_api_src_code
          path: bookstoreapi

      - name: verify dir
        run: ls -lrt

      - name: Java installation
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Maven build
        run: mvn -B install --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookstore_api
          path: target/*.jar
